{{- /*
  This secret contains the credentials to access the mysql db. Actullay, it is not used 
  by the Job Manager, because it takes the credentials from the configmap (at the moment), 
  but it is used by the mysql helm chart (auth.existingSecret). This is needed because while
  the name of the existing secret is rendered using the tpl, function, if the password is set
  with auth.password it is not possible to use the tpl function 
  This will not work:
    job-manager-backend:
      auth:
        password: "{{ tpl .Values.global.icos.jobManager.dbPassword . }}"
  This works:
    job-manager-backend:
      auth:
       existingSecret: "{{ .Release.Name }}-job-manager-backend-credentials"
 */ -}}

apiVersion: v1
kind: Secret
data:
  mysql-password: {{ tpl .Values.configMap.dbPassword . | b64enc }}
  mysql-root-password: {{ tpl .Values.configMap.dbPassword . | b64enc }}
metadata:
  name: {{ include "job-manager.fullname" . }}-backend-credentials
type: Opaque
