apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jobmanager-mysql
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-jobmanager-mysql" .Release.Name)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $mysqlPassword := (get $secretData "mysql-password") | default (randAlphaNum 32 | b64enc) }}
  {{- $mysqlRootPassword := (get $secretData "mysql-root-password") | default (randAlphaNum 32 | b64enc) }}
  mysql-password: {{ $mysqlPassword | quote }}
  mysql-root-password: {{ $mysqlRootPassword | quote }}