apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coordination-module.fullname" . }}
  labels:
    {{- include "coordination-module.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coordination-module.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coordination-module.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coordination-module.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if (tpl .Values.extraCertsBundle.configmapName .) }}
      volumes:
          - configMap:
              name: {{ tpl .Values.extraCertsBundle.configmapName . }}
            name: extra-certs-bundle
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "coordination-module.fullname" . }}
          livenessProbe:
            httpGet:
              path: "/health/liveness"
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: "/health/readiness"
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if (tpl .Values.extraCertsBundle.configmapName .) }}
          volumeMounts:
            - mountPath: /usr/lib/ssl/certs/icos-extra-certs.crt
              name: extra-certs-bundle
              subPath: {{ tpl .Values.extraCertsBundle.configmapKey . }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
